
 /*------------------------------------------------------------------------
    File        : test3
    Purpose     :
    Syntax      :
    Description :
    Author(s)   : ZipingWa
    Created     : Thu Mar 02 15:19:20 CET 2017
    Notes       :
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

BLOCK-LEVEL ON ERROR UNDO, THROW.

//TODO hello:
CLASS test3:

END CLASS.
