 
 /*------------------------------------------------------------------------
    File        : UserBrowser
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : ZipingWa
    Created     : Fri Nov 02 13:25:26 CET 2018
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

BLOCK-LEVEL ON ERROR UNDO, THROW.

CLASS Playground.Mips.UI.Browser.UserBrowser: 

END CLASS.