 
 /*------------------------------------------------------------------------
    File        : WindowManager
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : ZipingWa
    Created     : Thu Oct 18 11:14:19 CEST 2018
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

BLOCK-LEVEL ON ERROR UNDO, THROW.

CLASS Playground.Mips.App.WindowManager: 

END CLASS.