
 /*------------------------------------------------------------------------
    File        : GpSiteDispatcher
    Purpose     :
    Syntax      :
    Description :
    Author(s)   : ZipingWa
    Created     : Fri Nov 02 13:18:25 CET 2018
    Notes       :
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

BLOCK-LEVEL ON ERROR UNDO, THROW.

CLASS Playground.Mips.Model.Dispatcher.GpSiteDispatcher:

    METHOD PUBLIC VOID HandleToolCommand(  ):

        RETURN.

    END METHOD.

END CLASS.
